### ISSUE TITLE
Need RPM spec files

### ISSUE THREAD

**Issue by nward** [wanduow/openli#11]
Right now there's just Debian stuff, would be great to have RPM bits.

I intend to provide a PR with specs and gitlab-ci things to build them.

**Comment by salcock** [comment]
Getting pretty close to *finally* getting this sorted. I've got working RPMs for libtrace, libwandio and libwandder so it's just a matter of writing a .spec file for OpenLI itself and integrating it into our automated package building system.

**Comment by nward** [comment]
Gosh!

Are those other ones public? I got the openLI one almost done so can submit it once I have some others to test against.

I’d started on those others, but you know, life etc.

**Comment by salcock** [comment]
Yep, just pushed the libtrace RPMs to our bintray.

Follow the instructions at https://github.com/LibtraceTeam/libtrace/wiki/Installing-Libtrace and you should get access to everything you need.

**Comment by salcock** [comment]
Finally found some time to sit down and just *do* it.

All future releases will have .rpms built and uploaded automatically to [Bintray](https://bintray.com/beta/#/wand/OpenLI-rpm?tab=packages).

Hopefully later on today I'll manually upload some packages for 1.0.2 as well.
