### ISSUE TITLE
Add support for Jmirror encapsulation

### ISSUE THREAD

**Issue by salcock** [wanduow/openli#15]
Jmirror is a special encapsulation format used by Juniper E and MX devices for mirroring traffic based on a particular set of criteria (such as a RADIUS username). This is an easy method for our Juniper users to get their devices to mirror an intercept target's traffic into an OpenLI collector, but we'll need to strip the jmirror headers and replace them with a proper ETSI encapsulation.

This will be almost exactly the same as what we already support for ALU mirroring, just with a slightly different header format.

Relevant docs:
  * https://wiki.wireshark.org/jmirror
  *  https://www.juniper.net/documentation/en_US/junos/topics/concept/subscriber-management-subscriber-secure-policy-radius-header.html

Make sure we acquire some useful testing examples and include a test in our test suite for this format.

**Comment by salcock** [comment]
Code is complete and has passed rudimentary testing as of 32009bde0ddd5686fb9956605bd9c7be12b5d3b1 -- will keep this issue open until I've sorted out some semi-automated testing.

**Comment by tjharman** [comment]
Thank you very much!

**Comment by salcock** [comment]
Managed to confirm that the Jmirror code is working with a second set of traces from another source.

That's probably enough for me to assume the feature is ready to be included in the 1.0.3 release.

**Comment by tjharman** [comment]
Fantastic news, thanks again Shane.

**Comment by li-guy** [comment]
There is no  listener for the Jmirror udp packets to be received by, so there are a lot of Destination unreachable / Port unreachable packets being returned.  a workaround for now  'nc -ul -p [udp_port] >> /dev/null'

**Comment by salcock** [comment]
@li-guy Yeah, I was operating under the assumption that the user would provide their own Jmirror listener and run that on the collector alongside OpenLI.

I could add an extra binary to OpenLI that acts as a listener and gets spun up whenever a collector realises that it needs to do some Jmirror interception, if that's something that people want or need. It wouldn't be too difficult, but it will be another piece of software to manage and maintain so I only want to be doing it if it is something that genuinely adds value for our users.
