### ISSUE TITLE
Bug with UDP segment and fragment IP datagram

### ISSUE THREAD

**Issue by quangvnm** [wanduow/openli#27]
Hello,

### Issue:
We encountered a bug with UDP segment (mostly INVITE message where we 've seen one message of 1800bytes, fragmented in to two IP datagram). This UDP segment isn't intercepted and isn't sent to mediator

### Context
- Everything is in UDP (SIP, RTP)
- Some SIP client will send a big INVITE message and so it is broken mostly into two IP datagrams
- This message isn't intercepted

### Analyze
After digging into the code we found out that the following code has some problems.

Firslty, the SIP message is correctly concatednated from multiple IP datagram into a buffer sip_message
And then the following code will call a function to try to parse the message:
https://github.com/wanduow/openli/blob/fb3f13937c7914dbb092bb63cf09cbcbb20f404c/src/collector/collector_sync_voip.c#L1575

If we look several lines above this one, we find that:
https://github.com/wanduow/openli/blob/fb3f13937c7914dbb092bb63cf09cbcbb20f404c/src/collector/collector_sync_voip.c#L1548-L1551
`pktref = NULL`

so in the `parse_next_sip_message`:
https://github.com/wanduow/openli/blob/0a7e614562c0096fa04a49fc50cbd75a327c7e6d/src/collector/sipparsing.c#L128-L142
The code to reassemble the *tcp* stream is called, though we don't need it because it it *udp* and it seems to me that the message is already concatenated into buffer `p->sipmesage` before hand.
Anyway, the function `get_next_tcp_reassembled` will return 0 because of the check at the beginning of this function.
So `parse_next_sip_message` will return 0 instead of parsing the concatenated fragment.

And the INVITE message is discarded just after that.

### "Dirty" fix
If we disable the line for tcp reassembled:
https://github.com/wanduow/openli/blob/fb3f13937c7914dbb092bb63cf09cbcbb20f404c/src/collector/collector_sync_voip.c#L1548-L1551
It will work as attended for UDP stream, no more drops, but it isn't an elegant way and it doesn't support TCP then.

**Comment by salcock** [comment]
Thanks once again for the detailed bug report.

I think I have a reasonable solution for this, but I'll have to spend a bit of time running some tests to make sure it actually resolves the problem.

Will update this issue when I'm happy that I have a fix.

**Comment by quangvnm** [comment]
Thank once again too, @salcock :)

**Comment by salcock** [comment]
Hopefully, this has been fixed in the main wanduow/develop branch as of 58229160d6ca45a6a5ea52d031f9363117d45c43.

Feel free to re-open if you are still noticing problems.
