### ISSUE TITLE
Allow RADIUS Calling-Station-ID to be used as a target identifier

### ISSUE THREAD

**Issue by salcock** [wanduow/openli#38]
For some ISPs, RADIUS username is not a useful identifier. Instead, the customer CPE just uses a default set of credentials and the real auth happens based on the Calling Station ID that has been injected by the fibre provider.

Therefore we need to allow CSID to be used as an alternative method of inferring target identity from RADIUS packets -- this would likely have to be mutually exclusive from username, and we'll need some high quality documentation to explain which options should be used under various circumstances.

**Comment by tjharman** [comment]
I'm happy to write documentation.

**Comment by salcock** [comment]
#42 should meet the requirements for this feature (and hopefully a little more than that!).

I've got a little more testing that I'd like to do internally, but the code that has been written so far should be enough to warrant crossing this issue off.
