### ISSUE TITLE
Fix outstanding HI1 Operations message issues

### ISSUE THREAD

**Issue by salcock** [wanduow/openli#77]
Still having problems with HI1 Operations messages that are not able to be properly parsed by recipients.

Let's try to make sure our message matches the example given below as much as possible, and try to push ahead with some testing with an agency as soon as we can.

An example expected message from NZP:

```
PS-PDU SEQUENCE
{
  pSHeader PSHeader
  {
    li-psDomainId OBJECT IDENTIFIER = {itu-t(0) identified-organization(4) 0 2 2 5 1 14}
    lawfulInterceptionIdentifier LawfulInterceptionIdentifier = 31.33.34.33.30.39.31.30.30.34 [1343091004]
    authorizationCountryCode PrintableString = "NZ"
    communicationIdentifier CommunicationIdentifier
    {
      networkIdentifier NetworkIdentifier
      {
        operatorIdentifier OCTET STRING = 31.32.39.37.37 [12977]
      }
      deliveryCountryCode PrintableString = "NZ"
    }
    sequenceNumber INTEGER = 0
    timeStamp GeneralizedTime = "20200924011407.086Z"
    timeStampQualifier TimeStampQualifier = timeOfMediation
  }  
  payload Payload  {    
    hI1-Operation HI1-Operation    
    {      
      liActivated Notification      
      {        
        domainID OBJECT IDENTIFIER = {itu-t(0) identified-organization(4) 0 2 2 0 1 6}        
        lawfulInterceptionIdentifier LawfulInterceptionIdentifier = 31.33.34.33.30.39.31.30.30.34 [1343091004]        
        communicationIdentifier CommunicationIdentifier        
        {          
          network-Identifier Network-Identifier          
          {            
            operator-Identifier OCTET STRING = 31.32.39.37.37 [12977]          
          }
        }
        timeStamp TimeStamp
        {
          localTime LocalTimeStamp
          {
            generalizedTime GeneralizedTime = "20200924011407.086Z"
            winterSummerIndication ENUMERATED = notProvided
          }
        }
        national-HI1-ASN1parameters National-HI1-ASN1parameters
        {
          domainID OBJECT IDENTIFIER = {itu-t(0) identified-organization(4) 0 2 2 0 1 6}
          countryCode PrintableString = "NZ"
        }
      }
    }
  }
}

**Comment by salcock** [comment]
One of the key problems is that OpenLI is currently using the definition of CommunicationIdentifier from the LI-PS-PDU spec document:

```
CommunicationIdentifier ::= SEQUENCE
{
        networkIdentifier                               [0] NetworkIdentifier,
        communicationIdentityNumber             [1] INTEGER (0..4294967295) OPTIONAL,
                -- in case of transport of HI1 messages not required
                -- Mandatory for CC and IRI, with certain exceptions (see 5.2.4)
        deliveryCountryCode                             [2] PrintableString (SIZE (2)) OPTIONAL,
                -- see clause 5.2.4
        ...,
        cINExtension                                    [3] CorrelationValues OPTIONAL
                -- To be used when a single INTEGER is not sufficient to identify
                -- a particular session (see clause 5.2.4)
}

NetworkIdentifier ::= SEQUENCE
{
        operatorIdentifier                      [0] OCTET STRING (SIZE(1..16)),
        networkElementIdentifier        [1] OCTET STRING (SIZE(1..16)) OPTIONAL,
        ...,
        eTSI671NEID                                     [2] Network-Element-Identifier OPTIONAL
                -- For network element identifier, use either networkElementIdentifier or eTSI671NEID
}
```

when we actually should be using the other "CommunicationIdentifier" from the HI2Operations document:

```
CommunicationIdentifier ::= SEQUENCE
{
        communication-Identity-Number   [0] OCTET STRING (SIZE (1..8)) OPTIONAL,                -- Temporary Identifier of an intercepted call to uniquely identify an intercepted call
                -- within the node. This parameter is mandatory if there is associated
                -- information sent over HI3interface (CClink, data,..) or when
                -- CommunicationIdentifier is used for IRI other than IRI-Report-record
                -- This parameter was called "call-Identity-Number" in V1.1.1 of ES 201 671 [i.5]
                -- The individual digits of the communication-Identity-Number shall be represented in
                -- ASCII format, e.g. "12345678" = 8 octets 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38.
                -- For subaddress option only "0"..."9" shall be used.
        network-Identifier                              [1] Network-Identifier,
        ...
}

Network-Identifier ::= SEQUENCE
{
        operator-Identifier                     [0] OCTET STRING (SIZE (1..5)),
                -- It is a notification of the NWO/AP/SvP in ASCII- characters.
                -- For subaddress option only "0"..."9" shall be used.
                -- The parameter is mandatory.
        network-Element-Identifier      [1] Network-Element-Identifier OPTIONAL,
        ...
}
```

Why we have two separate (and quite different!) definitions for the same thing in the ETSI LI standards is a mystery to me.

Even worse, operator identifiers in one case are limited to 5 (numeric?) characters (and are presumably not globally unique) but they can be 16 characters in the other (but must be globally unique). What is the best way to handle this discrepancy?

**Comment by primal100** [comment]
Just had a quick look over the libwandder code and saw the domain ID for ETSI232 LI_PS_PDU. Is that the only standard OpenLI uses? 

HI2 Operations is older and generally ETSI232 LI_PS_PDU is the later, more up to date way of doing things. The reason older things still exist, like the older Communication Identifier is just for backward compatibility. There are mediation systems sending data to Monitoring Centres still using the same standards for the last 15 years and there is no urge to update any time soon. In particular IRI for Circuit-Switched calls. For wireline, probably nothing has changed for some of these operators in 20+ years. So nothing gets deprecated in these standards.

So generally, assuming you are only using the ETSI232 LI_PS_PDU, you should use the ETSI232 way of doing things, which means the first CommunicationIdentifier you listed. So it's strange that they can't parse it. Are they using a different standard for HI1?

**Comment by primal100** [comment]
OK I looked over some sample messages and I get it now. The ETSI232 standards allows to encode a traditional ETSI/3GPP HI1 Operation as the payload. So I see now why you need both types of CommunicationIdentifier, one in the header and one in the payload. Why ETSI232 doesn't have it's own way of encoding HI1 Operations instead of simply including a full traditional ETSI/3GPP PDU is a bit of mystery as you end up with a lot of duplication information being sent. 

I think the limitation to only use digits is only in some cases, in samples I have alphabetic charcters are sent. I'm not sure about the length though, maybe just send the first 5 characters?

**Comment by salcock** [comment]
Yeah, these comments more or less exactly describe my experience with learning about this problem :)

It's very silly and frustrating from an implementation perspective (especially the direct re-use of the term "CommunicationIdentifier"), and is an unfortunate reminder of the vested interests that have a big influence in writing the standards.

For now, I'm truncating to use the first 5 characters as you suggested but also allowing the user to configure a specific `altoperatorid` which they can use to set this value specifically if need be.

**Comment by salcock** [comment]
Ran some successful tests today using our `develop` branch, so I think we are ready to close this for now.
