### ISSUE TITLE
Use P-Asserted-Identity and Remote-Party-ID for target detection

### ISSUE THREAD

**Issue by dalason-dev** [wanduow/openli#80]
I have a question regarding the target detection of the caller. As far as I understand, openli does not use the "From:" header, because it can be spoofed, but instead uses the (Proxy-)Authorization header. However, this header does not necessarily contain the phone number. But the LEAs supply the targets as phone numbers, not as sip users (here in germany).

Therefore it would be very nice if not just the (Proxy-)Authorization header were used to detect target callers, but also the headers "P-Asserted-Identity" and "Remote-Party-ID", which usually contain the phone number. Would it be possible for you to implement this?

**Comment by salcock** [comment]
Hi,

Yes, absolutely we would like to be able to support this.

I would need some example pcaps containing SIP packets using these headers to do this development work. If you (or anyone else reading this) are able to help out, then send me an email (shane.alcock@waikato.ac.nz) and we can collaborate to get this feature added.

**Comment by salcock** [comment]
Code supporting this is now in `develop`, just waiting on feedback from our testing users to confirm that this works for them.

Will keep open for now until that confirmation comes through, but with any luck this shouldn't require any more work.

**Comment by salcock** [comment]
Closing for now, reopen if anyone notices any problems.
