### ISSUE TITLE
OpenLI: Error while trying to bind provisioner listening socket: Cannot assign requested address.

### ISSUE THREAD

**Issue by abdulkadirsalumlu** [wanduow/openli#89]
When we start provisioner, we get error as screenshot in below. We wrote collector address to clientaddr and port field.  What we should write to updateaddr and port ? 

![image](https://user-images.githubusercontent.com/65689135/132523013-7df00099-123d-4420-8741-1b108860c9ee.png)

provisioner-config-yaml file

clientaddr: 192.168.80.144
clientport: 9001

mediationaddr: 192.168.80.146
mediationport: 12001

updateaddr: 192.168.80.145
updateport: 8992

**Comment by salcock** [comment]
Hi,

In the provisioner config, you actually want to put the **provisioner's** IP address in each of the `addr` config options.

These config options tell the provisioner which address and port to listen on for incoming connections from the other components, as well as where to listen for REST API requests (the `updateaddr` and `updateport` options are the REST API options).
