### ISSUE TITLE
Additional zero at the end of li-psDomainId

### ISSUE THREAD

**Issue by thuroc** [wanduow/openli#91]
Hello,

at the end of the last year we've run an initial test with our public authorities in germany to establish a lawful interception trunk to the german police.

In this test we run into a problem with the PSHeader li-psDomainId. The authority complained, that there was an additionaly zero at the end of this ID. In the trace of this test we could see that the li-psDomainId 0.4.0.2.2.5.1.17.0 was commited. This last zero at the end was the reason the authority was unable to complete the test.

Even after taking a closer look at the ETSI TR 102 503, we couldn't find out where this last number should stand for. In addition, we have not found an option in openLI to switch off this additional number.

Can you help us to make the software compatible with german authorities?

Regards
Sven

**Comment by salcock** [comment]
Hello,

Thanks for reporting this issue.

I've looked into it and you are correct -- there is a bug in libwandder that is causing an extra 0 to be appended to the end of the LI PS Domain ID field.

I've patched the bug and pushed out a new libwandder release -- if you upgrade to libwandder 2.0.4 on your OpenLI collector, the issue should be resolved.

Please let me know if you are still having problems after upgrading, or if you encounter any other errors while testing with the German authorities.

**Comment by thuroc** [comment]
Hello salcock,

thank you for your very fast response and fix for that issue.

I've reinstalled the system and now all IDs are fine.

Thank you very much
